version: "3.3"

services:
  db:
    image: postgres
    container_name: sdb-postgres
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=santedb
      - POSTGRES_PASSWORD=SanteDB123
    restart: always

  santedb:
    image: santesuite/santedb-icdr:latest
    container_name: santedb-icdr
    environment:
      - SDB_FEATURE=LOG;DATA_POLICY;AUDIT_REPO;ADO;PUBSUB_ADO;RAMCACHE;SEC;SWAGGER;OPENID;FHIR;HL7;HDSI;AMI;BIS
      - SDB_DB_MAIN=server=sdb-postgres;port=5432; database=santedb; user id=santedb; password=SanteDB123; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;
      - SDB_DB_AUDIT=server=sdb-postgres;port=5432; database=auditdb; user id=santedb; password=SanteDB123; pooling=true; MinPoolSize=5; MaxPoolSize=15; Timeout=60;
      - SDB_DB_MAIN_PROVIDER=Npgsql
      - SDB_FHIR_AUDIT_EP=http://fs-wks01:8989/fhir/Audit
      - SDB_DB_AUDIT_PROVIDER=Npgsql
      - SDB_REDIS_SERVER=sdb-redis:6379
      - SDB_DATA_POLICY_ACTION=HIDE
      - SDB_DELAY_START=5000
    ports:
<<<<<<< HEAD
      - 8080:8080
      - 2100:2100
    volumes:
      - sdb-mpi-seed:/santedb/data
      - sdb-mpi-config:/santedb/config
      - sdb-mpi-app:/santedb/applets
=======
      - "8080:8080"
      - "2100:2100"
>>>>>>> develop
    depends_on:
      - db
    restart: always
    
<<<<<<< HEAD
volumes:
  sdb-mpi-seed:
  sdb-mpi-config:
<<<<<<< HEAD
  sdb-mpi-app:
=======
  sdb-mpi-app:
>>>>>>> 60de2065ab18383830656a0aea72cf3af3ea45f8
=======
>>>>>>> develop
